"""can_verify added

Revision ID: 4f79df36b225
Revises: a19114fdb671
Create Date: 2020-11-28 19:53:51.440876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f79df36b225'
down_revision = 'a19114fdb671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('can_verify', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('hash_verified', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hash_verified')
    op.drop_column('user', 'can_verify')
    # ### end Alembic commands ###
