"""removed hash table

Revision ID: a19114fdb671
Revises: e4f4dbe29010
Create Date: 2020-11-28 19:20:36.090766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19114fdb671'
down_revision = 'e4f4dbe29010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hash')
    # ### end Alembic commands ###
