"""added hash table

Revision ID: e4f4dbe29010
Revises: f8a2e80b7b48
Create Date: 2020-11-28 18:43:30.114123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f4dbe29010'
down_revision = 'f8a2e80b7b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_key', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_key')
    # ### end Alembic commands ###
